### PR TITLE
[ADD] clouder-samba-dc: Create Dockerfile

### PR DESCRIPTION
**Pull request by tedsalmon**
* Create Dockerfile based on clouder/base:3.4
* Install Samba4 DC and prep it for setup
* Update README.md

### CODE REVIEW

**Comment by tedsalmon** [comment]
Provided that we don't actually want to configure the DC in the Dockerfile, this is ready for review. Let me know if I missed anything.

Thanks!

**Comment by lasley** [comment]
So in terms of the way Clouder typically does things, there would be an exec and a data. We're not making that differentiation quite yet though just for ease.

In the data ones, there is typically all the config that would go in etc. We would want to have good default configs there & copy them to where they need to go.

In terms of things like which LDAP server to connect to, shares to advertise, etc. - no need to config.

**Comment by tedsalmon** [comment]
Hey @lasley,

Sorry for the late reply. So, nothing really can be configured until the domain is provisioned. All of the required config files are created when you run 
```
samba-tool domain provision
```

My suspicion is that clouder will need to take care of that part of the config anyways.

**Comment by lasley** [comment]
Merging, this will be redesigned in LABS-423 anyways

**Pull request merged**
